version: '3.8'
services:
  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3006:3000"
    volumes:
      - ./react-frontend:/react-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
<<<<<<< HEAD
    stdin_open: true
    tty: true
=======
>>>>>>> f6a4957 (一応動くけど、重い気がする)
